### ISSUE TITLE
frappesdek installation failure

### ISSUE THREAD

**Issue by odhiambo** [frappe/helpdesk#1055]
Hi. I am trying to install frappedesk, but it fails:

```
(env) [frappe@gw ~/frappe-bench]$ bench get-app frappedesk
Getting frappedesk
$ git clone https://github.com/frappe/frappedesk.git  --depth 1 --origin upstream
Cloning into 'frappedesk'...
remote: Enumerating objects: 598, done.
remote: Counting objects: 100% (598/598), done.
remote: Compressing objects: 100% (497/497), done.
remote: Total 598 (delta 104), reused 430 (delta 78), pack-reused 0
Receiving objects: 100% (598/598), 5.65 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (104/104), done.
Ignoring dependencies of frappedesk. To install dependencies use --resolve-deps
Installing frappedesk
$ /opt/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /opt/frappe/frappe-bench/apps/frappedesk
$ yarn install
yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > tailwindcss@3.2.6" has unmet peer dependency "postcss@^8.0.9".
[4/4] Building fresh packages...
$ husky install && cd desk && yarn install
[##################################################################################################################################################################################################################################] 429/429husky - Git hooks installed
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/echarts/-/echarts-5.4.1.tgz: incorrect data check".
info If you think this is a bug, please open a bug report with the information provided in "/opt/frappe/frappe-bench/apps/frappedesk/desk/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error https://registry.yarnpkg.com/@esbuild/android-arm64/-/android-arm64-0.16.17.tgz: incorrect data check
error https://registry.yarnpkg.com/@esbuild/win32-x64/-/win32-x64-0.16.17.tgz: incorrect data check
error https://registry.yarnpkg.com/@esbuild/win32-ia32/-/win32-ia32-0.16.17.tgz: incorrect data check
error https://registry.yarnpkg.com/@esbuild/linux-ia32/-/linux-ia32-0.16.17.tgz: incorrect data check
error https://registry.yarnpkg.com/@esbuild/openbsd-x64/-/openbsd-x64-0.16.17.tgz: incorrect data check
error https://registry.yarnpkg.com/@esbuild/linux-riscv64/-/linux-riscv64-0.16.17.tgz: incorrect data check
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR:
subprocess.CalledProcessError: Command 'yarn install' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.11/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 242, in install
    install_app(
  File "/usr/local/lib/python3.11/site-packages/bench/app.py", line 581, in install_app
    bench.run("yarn install", cwd=app_path)
  File "/usr/local/lib/python3.11/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError
(env) [frappe@gw ~/frappe-bench]$
```

How can I solve this?
Thank you.

**Comment by ssiyad** [comment]
Probably an issue with your node version. Try with v16 or v18

**Comment by odhiambo** [comment]
(env) [frappe@gw ~/frappe-bench]$ node --version
v16.19.1

**Comment by RitvikSardana** [comment]
Part of old helpdesk, hence closing
