### ISSUE TITLE
Installtion Failure

### ISSUE THREAD

**Issue by dineshliyanage0** [frappe/helpdesk#1057]
# An error occurred while installing frappedesk: Module import failed for SLA, the DocType you're trying to open might be deleted.

Installing frappedesk...
Updating DocTypes for frappedesk    : [=====================                   ] 53%An error occurred while installing frappedesk: Module import failed for SLA, the DocType you're trying to open might be deleted.<br> Error: cannot import name 'get_system_timezone' from 'frappe.utils' (/home/frappe/frappe-bench/apps/frappe/frappe/utils/__init__.py)
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 240, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1327, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/frappedesk/frappedesk/frappedesk/doctype/sla/sla.py", line 11, in <module>
    from frappe.utils import (
ImportError: cannot import name 'get_system_timezone' from 'frappe.utils' (apps/frappe/frappe/utils/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 413, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 294, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 80, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1077, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 909, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 906, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 406, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 491, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 244, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for SLA, the DocType you're trying to open might be deleted.<br> Error: cannot import name 'get_system_timezone' from 'frappe.utils' (apps/frappe/frappe/utils/__init__.py)

**Comment by ssiyad** [comment]
We don't support v13. You can use v14/15 or manually revert https://github.com/frappe/helpdesk/pull/1034
