### ISSUE TITLE
Unable to install helpdesk on ubuntu

### ISSUE THREAD

**Issue by prasathsekar** [frappe/helpdesk#1216]
bench --site helpdesk.test install-app helpdesk

Installing helpdesk...
An error occurred while installing helpdesk: cannot import name 'Criterion' from 'frappe.database.database' (/home/frappe/frappe-bench/apps/frappe/frappe/database/database.py)
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 293, in install_app
    _install_app(app, verbose=context.verbose)
  File "apps/frappe/frappe/installer.py", line 179, in install_app
    out = frappe.get_attr(before_install)()
  File "apps/frappe/frappe/__init__.py", line 1463, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1205, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/helpdesk/helpdesk/setup/install.py", line 6, in <module>
    from .welcome_ticket import create_welcome_ticket
  File "apps/helpdesk/helpdesk/setup/welcome_ticket.py", line 3, in <module>
    from helpdesk.helpdesk.doctype.hd_ticket.hd_ticket import (
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 11, in <module>
    from frappe.database.database import Criterion, Query
ImportError: cannot import name 'Criterion' from 'frappe.database.database' (apps/frappe/frappe/database/database.py)

Unable to run helpdesk in the production, showing the above error

**Comment by ssiyad** [comment]
What is
- Helpdesk version
- Frappe framework version

**Comment by prasathsekar** [comment]
During the installation of Helpdesk, the is no version is mentioned. Following the below installation method

https://github.com/frappe/helpdesk

bench --site helpdesk.test install-app helpdesk

Frappe framework version --> Version 13, below is the installation command line

bench init frappe-bench --frappe-branch version-13

**Comment by ssiyad** [comment]
Helpdesk does not support version-13

**Comment by prasathsekar** [comment]
Can you help me with helpdesk supported version of frappe framework ?
