### ISSUE TITLE
Unable to Create a New Agent

### ISSUE THREAD

**Issue by singhranbir** [frappe/helpdesk#1318]
While Opening a HD Agent List. I am getting a below error, due to this i am unable to create a new Agent.

### App Versions
```
{
	"erpnext": "14.31.2",
	"frappe": "14.41.0",
	"helpdesk": "0.9.1"
}
```
### Route
```
List/HD Agent/List
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 94, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1619, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 801, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/reportview.py", line 29, in get
    data = compress(execute(**args), args=args)
  File "apps/frappe/frappe/desk/reportview.py", line 65, in execute
    return DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 196, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 236, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabHD Agent.agent_name' in 'field list'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "HD Agent",
		"fields": "[\"`tabHD Agent`.`name`\",\"`tabHD Agent`.`owner`\",\"`tabHD Agent`.`creation`\",\"`tabHD Agent`.`modified`\",\"`tabHD Agent`.`modified_by`\",\"`tabHD Agent`.`_user_tags`\",\"`tabHD Agent`.`_comments`\",\"`tabHD Agent`.`_assign`\",\"`tabHD Agent`.`_liked_by`\",\"`tabHD Agent`.`docstatus`\",\"`tabHD Agent`.`idx`\",\"`tabHD Agent`.`is_active`\",\"`tabHD Agent`.`agent_name`\"]",
		"filters": "[]",
		"order_by": "`tabHD Agent`.`modified` DESC",
		"start": 0,
		"page_length": 20,
		"view": "List",
		"group_by": "`tabHD Agent`.`name`",
		"with_comment_count": true
	},
	"freeze": false,
	"freeze_message": "Loading...",
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.reportview.get"
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'tabHD Agent.agent_name' in 'field list'\")"
}
```

Kindly help. @ssiyad

**Comment by Shivam327** [comment]
After Update all are facing the same error.

![image](https://github.com/frappe/helpdesk/assets/23412311/29712be1-2edd-4dde-9d3c-6d0358f383dd)

**Comment by ssiyad** [comment]
@Shivam327 can you try again with latest commit? This should be fixed now

**Comment by Shivam327** [comment]
@singhranbir Yes it's Working
