### ISSUE TITLE
Custom fields not shown in ticket dialog

### ISSUE THREAD

**Issue by michellealva** [frappe/helpdesk#1379]
![2023-07-28 18 51 59](https://github.com/frappe/helpdesk/assets/50285544/3c4b0da1-c933-4ece-b1b2-4f8a0c79f4b0)

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    response = frappe.api.handle()
               ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1650, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 30, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/helpdesk/helpdesk/api/ticket.py", line 73, in create_new
    ticket_doc.insert(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 280, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 550, in _validate
    self._validate_mandatory()
  File "apps/frappe/frappe/model/document.py", line 885, in _validate_mandatory
    raise frappe.MandatoryError(
frappe.exceptions.MandatoryError: [HD Ticket, 7]: custom_site_name
```

**Comment by nextchamp-saqib** [comment]
It was a customization issue. Should be fixed now.
