### ISSUE TITLE
Auto save not working while changing Team

### ISSUE THREAD

**Issue by michellealva** [frappe/helpdesk#1383]
Check GIF

https://github.com/frappe/helpdesk/assets/50285544/185e59a1-685b-4955-8d05-e8030e149058

I also tried changing the team from inside the desk. Got this error:

 ```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    response = frappe.api.handle()
               ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1650, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 30, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 36, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 326, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 378, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1108, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 936, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1306, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1288, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 933, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 171, in on_update
    self.remove_assignment_if_not_in_team()
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 243, in remove_assignment_if_not_in_team
    current_assigned_agent_doc = self.get_assigned_agent()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 357, in get_assigned_agent
    if self._assign:
       ^^^^^^^^^^^^
AttributeError: 'HDTicket' object has no attribute '_assign'

(anonymous) @ request.js:456
```

**Comment by nextchamp-saqib** [comment]
fixed: [e1011bc](https://github.com/frappe/helpdesk/commit/e1011bc8b140a569608c082ded0c2972be532cc0)
