### ISSUE TITLE
Canned responses list view broken

### ISSUE THREAD

**Issue by michellealva** [frappe/helpdesk#1451]
<img width="1680" alt="image" src="https://github.com/frappe/helpdesk/assets/50285544/8e571812-8e0b-43d4-b32f-60a54504e94c">

```
index-b9055c61.js:27 Error: Missing required param "id"
    at Object.u [as stringify] (index-b9055c61.js:42:7020)
    at Object.c [as resolve] (index-b9055c61.js:42:10362)
    at Object.A [as resolve] (index-b9055c61.js:42:18045)
    at Xm.fn (index-b9055c61.js:42:14188)
    at Xm.run (index-b9055c61.js:27:15573)
    at get value [as value] (index-b9055c61.js:27:24146)
    at Xm.fn (index-b9055c61.js:42:14236)
    at Xm.run (index-b9055c61.js:27:15573)
    at get value [as value] (index-b9055c61.js:27:24146)
    at Xm.fn (index-b9055c61.js:42:14520)
```

**Comment by ssiyad** [comment]
https://github.com/frappe/helpdesk/pull/1452
