### ISSUE TITLE
Error on saving HD Ticket

### ISSUE THREAD

**Issue by vorasmit** [frappe/helpdesk#1518]
### App Versions
```
{
	"frappe": "15.0.0-dev",
	"helpdesk": "0.10.0",
	"wiki": "2.0.0"
}
```
### Route
```
Form/HD Ticket/571
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    response = frappe.api.handle()
               ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1654, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 30, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 36, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 329, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 364, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1072, in run_before_save_methods
    self.run_method("before_save")
  File "apps/frappe/frappe/model/document.py", line 935, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1306, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1288, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 932, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 167, in before_save
    self.apply_sla()
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 692, in apply_sla
    sla.apply(self)
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py", line 123, in apply
    self.handle_status(doc)
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py", line 136, in handle_status
    self.set_first_responded_at(doc)
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py", line 149, in set_first_responded_at
    doc.first_response_time = self.calc_elapsed_time(start_at, end_at)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py", line 276, in calc_elapsed_time
    today_weekday = weekdays[today.weekday()]
                             ^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'weekday'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":571,\"owner\":\"prashant@smbcatalyst.com\",\"creation\":\"2023-08-19 10:42:12.475712\",\"modified\":\"2023-08-22 08:11:01.206036\",\"modified_by\":\"deepesh@erpnext.com\",\"docstatus\":0,\"idx\":58,\"subject\":\"Issue in 3B report\",\"raised_by\":\"prashant@smbcatalyst.com\",\"status\":\"Replied\",\"priority\":\"Investigation\",\"custom_reference_module\":\"Accounts\",\"custom_is_enterprise\":1,\"ticket_type\":\"To Validate\",\"agent_group\":\"L2 India Compliance\",\"custom_site_name\":\"guninagroup.frappe.cloud\",\"custom_dashboard_link\":\"https://frappecloud.com/dashboard/sites/guninagroup.frappe.cloud\",\"custom_app\":\"ERPNext\",\"custom_plan\":\"USD 200\",\"description\":\"<p>Hi, The issue is on <a target=\\\"_blank\\\" rel=\\\"noopener noreferrer nofollow\\\" href=\\\"http://lotusc.frappe.cloud\\\">lotusc.frappe.cloud</a> site. We have migrated the sites to dedicated server still not allowint to raise issue thats why raised issue here as it is ctrical related to GSTR 3B and deadline is 20th Aug.</p><p>We are trying to understand from where the Amount in 3.1 (b) has came. But we couldnot identify. We checked with item wise sales register as well as GST itemised sales register. Can you just help us?</p><img src=\\\"/files/8QvtKIq.png\\\"><p></p>\",\"template\":\"Default\",\"response_by\":\"2023-08-21 12:00:00\",\"agreement_status\":\"Resolution Due\",\"resolution_by\":\"2023-08-22 18:00:00\",\"service_level_agreement_creation\":\"2023-08-19 10:42:12.475712\",\"first_response_time\":98154.15,\"first_responded_on\":\"2023-08-20 13:58:06.627973\",\"avg_response_time\":98152.79,\"opening_date\":\"2023-08-19\",\"opening_time\":\"10:42:12.475615\",\"contact\":\"prashant\",\"customer\":\"vikramtea.erpnext.com\",\"via_customer_portal\":1,\"doctype\":\"HD Ticket\",\"__last_sync_on\":\"2023-08-22T08:19:21.780Z\",\"__unsaved\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery370095324451256802821": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 556,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'str' object has no attribute 'weekday'",
	"_exc_source": "helpdesk (app)"
}
```

**Comment by vorasmit** [comment]
@ssiyad I guess it's not deployed to support.frappe.io, correct? We were still not able to update the status of issues.

**Comment by ssiyad** [comment]
This is deployed in Frappe Support. Let me check if this something else.

**Comment by vorasmit** [comment]
I guess there is a new issue which is not allowing to save tickets.

### App Versions
```
{
	"frappe": "15.0.0-dev",
	"helpdesk": "0.10.0",
	"wiki": "2.0.0"
}
```
### Route
```
Form/HD Ticket/702
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    response = frappe.api.handle()
               ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1671, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 30, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 36, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 329, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 364, in _save
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1072, in run_before_save_methods
    self.run_method("before_save")
  File "apps/frappe/frappe/model/document.py", line 935, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1306, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1288, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 932, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 164, in before_save
    self.apply_sla()
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 689, in apply_sla
    sla.apply(self)
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py", line 124, in apply
    self.handle_agreement_status(doc)
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py", line 210, in handle_agreement_status
    is_failed = self.is_first_response_failed(doc) or self.is_resolution_failed(doc)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py", line 225, in is_first_response_failed
    return doc.response_by < doc.first_responded_on
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'datetime.datetime' and 'str'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":702,\"owner\":\"arun.kumar@dfmfoods.com\",\"creation\":\"2023-08-23 17:49:10.296389\",\"modified\":\"2023-08-25 10:12:19.291619\",\"modified_by\":\"sanjay@erpnext.com\",\"docstatus\":0,\"idx\":39,\"subject\":\"e-Way bill generated but not linked with document\",\"raised_by\":\"arun.kumar@dfmfoods.com\",\"status\":\"Replied\",\"priority\":\"Investigation\",\"custom_reference_module\":\"Selling\",\"custom_is_enterprise\":0,\"ticket_type\":\"To Validate\",\"agent_group\":\"L2 India Compliance\",\"custom_site_name\":\"erp.dfmfoods.com\",\"custom_dashboard_link\":\"https://frappecloud.com/dashboard/sites/erp.dfmfoods.com\",\"custom_app\":\"ERPNext\",\"description\":\"<p>Dear Team,</p><p>For the below invoices, the system is showing that e-Way bill has been generated for this document but it is not showing. please refer to the below screenshots. Please look into this.</p><p>Bill no : <a target=\\\"_blank\\\" rel=\\\"noopener noreferrer nofollow\\\" href=\\\"https://erp.dfmfoods.com/app/sales-invoice/35022301167\\\">35022301167,35022301167</a></p><p></p><img src=\\\"/files/u3vxpL6.png\\\"><img src=\\\"/files/THNHZuP.png\\\">\",\"template\":\"Default\",\"sla\":\"SLA-Standard (Excludes FC Customers)\",\"response_by\":\"2023-08-24 11:49:11.163839\",\"agreement_status\":\"Resolution Due\",\"resolution_by\":\"2023-08-25 17:49:11.163839\",\"service_level_agreement_creation\":\"2023-08-23 17:49:11.163839\",\"first_response_time\":57172.46,\"first_responded_on\":\"2023-08-24 09:42:02.751770\",\"avg_response_time\":57170.86,\"opening_date\":\"2023-08-23\",\"opening_time\":\"17:49:10.296273\",\"contact\":\"arun.kumar-erp.dfmfoods.com\",\"customer\":\"erp.dfmfoods.com\",\"via_customer_portal\":1,\"doctype\":\"HD Ticket\",\"__last_sync_on\":\"2023-08-25T05:26:34.447Z\",\"__unsaved\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery370087684480184437551": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 729,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "TypeError: '<' not supported between instances of 'datetime.datetime' and 'str'",
	"_exc_source": "helpdesk (app)"
}
```

**Comment by ssiyad** [comment]
@vorasmit can you please share a video of when this happens?

**Comment by vorasmit** [comment]
https://github.com/frappe/helpdesk/assets/10496564/4223d0e2-d31b-4074-af2d-95a4eb928246

**Comment by ssiyad** [comment]
Oh! I assumed you were using customer/agent portal of Helpdesk. This looks like a side-effect of some magic. Let me check and fix ASAP

**Comment by ssiyad** [comment]
@vorasmit This must be fixed now. Please check and close this issue if everything works. Else, please let me know

**Comment by vorasmit** [comment]
Thank you so much for the prompt resolution and deploy.
