### ISSUE TITLE
Module import failed

### ISSUE THREAD

**Issue by NirajRegmi** [frappe/helpdesk#1540]
I am installing the frappe helpdesk in my environment but got the following issue.
Frappe version: 14.x.x
erpnext: 14.x.x

The error I reproduce is:

Installing helpdesk...
Updating DocTypes for helpdesk      : [============                            ] 30%An error occurred while installing helpdesk: Module import failed for HD Escalation Rule, the DocType you're trying to open might be deleted.<br> Error: No module named 'frappe.utils.telemetry'
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 240, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1327, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_escalation_rule/hd_escalation_rule.py", line 8, in <module>
    from helpdesk.utils import capture_event, publish_event
  File "apps/helpdesk/helpdesk/utils.py", line 8, in <module>
    from frappe.utils.telemetry import capture as _capture
ModuleNotFoundError: No module named 'frappe.utils.telemetry'

**Comment by ssiyad** [comment]
You need at-least Frappe v14.36. Please make sure you framework version is upto date
