### ISSUE TITLE
Existing Tickets are not opening

### ISSUE THREAD

**Issue by asoral** [frappe/helpdesk#1590]
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1622, in call
    return fn(*args, **newargs)
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/api.py", line 69, in get_one
    "assignee": get_assignee(ticket._assign),
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/api.py", line 95, in get_assignee
    if len(j) < 1:
TypeError: object of type 'NoneType' has no len()

**Comment by ssiyad** [comment]
Must be fixed be https://github.com/frappe/helpdesk/pull/1586

**Comment by JoSoG89** [comment]
> Must be fixed by #1586

I´m still that problem.
