### ISSUE TITLE
Error While Updating or Installing APP

### ISSUE THREAD

**Issue by Shivam327** [frappe/helpdesk#1601]
Installing helpdesk...
Updating DocTypes for helpdesk      : [==========================              ] 65%An error occurred while installing helpdesk: Module import failed for HD Ticket, the DocType you're trying to open might be deleted.<br> Error: No module named 'redis.commands'
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 245, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1342, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 24, in <module>
    from helpdesk.search import HelpdeskSearch
  File "apps/helpdesk/helpdesk/search.py", line 11, in <module>
    from redis.commands.search.field import TagField, TextField
ModuleNotFoundError: No module named 'redis.commands'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 415, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 297, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 287, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1090, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 917, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1279, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1261, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 914, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 408, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 506, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 249, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for HD Ticket, the DocType you're trying to open might be deleted.<br> Error: No module named 'redis.commands'

**Comment by infinity-sys** [comment]
Same problem, any solution?

**Comment by 0xhaval** [comment]
Same problem

**Comment by richardadinugraha** [comment]
same problem on frappe 14 ubuntu 22.04

**Comment by itsdaveit** [comment]
A new search feature has be introduced:
https://github.com/frappe/helpdesk/pull/1583
which uses redis.commands.search, which is not available in the older redis-py versions.
as a workaround i have done:

~/frappe-bench$ env/bin/pip uninstall redis
~/frappe-bench$ env/bin/pip install redis

which installed a more recent, but not officially compatible, but at least i was able to get the site up again...

<img width="860" alt="image" src="https://github.com/frappe/helpdesk/assets/9453135/4c42ec23-4755-4667-b26a-a8ce4af6ebfd">

**Comment by isreallee82** [comment]
thanks this worked! @itsdaveit
