### ISSUE TITLE
installing issue 

### ISSUE THREAD

**Issue by yahyaoudra** [frappe/helpdesk#1627]
An error occurred while installing helpdesk: (1045, "Access denied for user '_ee10910ef7c873ed'@'localhost' (using password: YES)")
Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -4902046684320067585

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 415, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 261, in install_app
    frappe.clear_cache()
  File "apps/frappe/frappe/__init__.py", line 897, in clear_cache
    frappe.cache_manager.clear_user_cache()
  File "apps/frappe/frappe/cache_manager.py", line 97, in clear_user_cache
    clear_global_cache()
  File "apps/frappe/frappe/cache_manager.py", line 110, in clear_global_cache
    clear_website_cache()
  File "apps/frappe/frappe/website/utils.py", line 394, in clear_website_cache
    clear_cache(path)
  File "apps/frappe/frappe/website/utils.py", line 389, in clear_cache
    for method in frappe.get_hooks("website_clear_cache"):
  File "apps/frappe/frappe/__init__.py", line 1511, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1474, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1430, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "apps/frappe/frappe/database/database.py", line 975, in get_global
    return self.get_default(key, user)
  File "apps/frappe/frappe/database/database.py", line 979, in get_default
    d = self.get_defaults(key, parent)
  File "apps/frappe/frappe/database/database.py", line 995, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/database.py", line 201, in sql
    self.connect()
  File "apps/frappe/frappe/database/database.py", line 115, in connect
    self._conn = self.get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 98, in get_connection
    conn = self._get_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 104, in _get_connection
    return self.create_connection()
  File "apps/frappe/frappe/database/mariadb/database.py", line 107, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '_ee10910ef7c873ed'@'localhost' (using password: YES)")

**Comment by RitvikSardana** [comment]
should be fixed now, re-open if the issue still persists
