### ISSUE TITLE
Helpdesk Setup Error

### ISSUE THREAD

**Issue by dineshpanchal93** [frappe/helpdesk#1908]
### App Versions
```
{
	"attendance_reconciliation": "0.0.1",
	"bank_connector_erpnext": "0.0.1",
	"bom_analysis": "0.0.1",
	"bulk_export": "0.0.1",
	"bulkqrcodegeneration": "0.0.2",
	"check_run": "15.1.2",
	"crm": "1.19.0",
	"custom_attendance": "0.0.1",
	"custom_emails": "0.0.1",
	"emailsapprovals": "0.0.1",
	"erpnext": "15.32.1",
	"frappe": "15.37.0",
	"gameplan": "0.0.1",
	"helpdesk": "0.10.0",
	"hrms": "15.25.2",
	"in_out_track": "0.0.1",
	"india_compliance": "15.12.1",
	"kentcamattendance": "0.0.1",
	"print_designer": "1.4.0",
	"raven": "1.6.6",
	"reports": "0.0.1",
	"twilio_integration": "0.0.1",
	"ultramsg_4_erpnext": "2.0.1"
}
```
### Route
```
setup-wizard/0
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 61, in setup_complete
    return process_setup_stages(stages, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 81, in process_setup_stages
    task.get("fn")(task.get("args"))
  File "apps/helpdesk/helpdesk/setup/setup_wizard.py", line 14, in setup_complete
    new_user = frappe.db.get_list("User", filters={"email": email}, limit=1, pluck="name")[
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"args": "{\"language\":\"English\",\"country\":\"India\",\"timezone\":\"Asia/Kolkata\",\"currency\":\"INR\",\"company_name\":\"Gladwin Techgen Private Limited\",\"company_abbr\":\"GTPL\",\"default_gst_rate\":\"18.0\",\"chart_of_accounts\":\"India - Chart of Accounts\",\"fy_start_date\":\"2024-04-01\",\"fy_end_date\":\"2025-03-31\",\"setup_demo\":0,\"enable_audit_trail\":0}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.page.setup_wizard.setup_wizard.setup_complete",
	"request_id": null
}
```
### Response Data
```
{
	"setup_wizard_failure_message": "Failed to execute method",
	"exception": "IndexError: list index out of range",
	"exc_type": "IndexError",
	"_exc_source": "helpdesk (app)"
}
```

### Version

Frappe Latest v15
Helpdesk Main Latest 

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"attendance_reconciliation": "0.0.1",
	"bank_connector_erpnext": "0.0.1",
	"bom_analysis": "0.0.1",
	"bulk_export": "0.0.1",
	"bulkqrcodegeneration": "0.0.2",
	"check_run": "15.1.2",
	"crm": "1.19.0",
	"custom_attendance": "0.0.1",
	"custom_emails": "0.0.1",
	"emailsapprovals": "0.0.1",
	"erpnext": "15.32.1",
	"frappe": "15.37.0",
	"gameplan": "0.0.1",
	"helpdesk": "0.10.0",
	"hrms": "15.25.2",
	"in_out_track": "0.0.1",
	"india_compliance": "15.12.1",
	"kentcamattendance": "0.0.1",
	"print_designer": "1.4.0",
	"raven": "1.6.6",
	"reports": "0.0.1",
	"twilio_integration": "0.0.1",
	"ultramsg_4_erpnext": "2.0.1"
}
```
### Route
```
setup-wizard/0
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1768, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 61, in setup_complete
    return process_setup_stages(stages, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 81, in process_setup_stages
    task.get("fn")(task.get("args"))
  File "apps/helpdesk/helpdesk/setup/setup_wizard.py", line 14, in setup_complete
    new_user = frappe.db.get_list("User", filters={"email": email}, limit=1, pluck="name")[
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"args": "{\"language\":\"English\",\"country\":\"India\",\"timezone\":\"Asia/Kolkata\",\"currency\":\"INR\",\"company_name\":\"Gladwin Techgen Private Limited\",\"company_abbr\":\"GTPL\",\"default_gst_rate\":\"18.0\",\"chart_of_accounts\":\"India - Chart of Accounts\",\"fy_start_date\":\"2024-04-01\",\"fy_end_date\":\"2025-03-31\",\"setup_demo\":0,\"enable_audit_trail\":0}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.page.setup_wizard.setup_wizard.setup_complete",
	"request_id": null
}
```
### Response Data
```
{
	"setup_wizard_failure_message": "Failed to execute method",
	"exception": "IndexError: list index out of range",
	"exc_type": "IndexError",
	"_exc_source": "helpdesk (app)"
}
```
```

**Comment by dineshpanchal93** [comment]
@RitvikSardana

**Comment by RitvikSardana** [comment]
@dineshpanchal93 

can you share ss of setup wizards?

**Comment by dineshpanchal93** [comment]
https://github.com/user-attachments/assets/61d70e0a-621d-4e15-b75f-47ee2084bde1

**Comment by RitvikSardana** [comment]
actually both steps please?
Previous also? @dineshpanchal93

**Comment by RitvikSardana** [comment]
U had helpdesk already installed, and then were you trying to install ERPNext @dineshpanchal93 ?

**Comment by dineshpanchal93** [comment]
Let me try with new SIte actually I did reinstall the sites. 

So I got this error.

**Comment by dineshpanchal93** [comment]
same problem with new site

![Screenshot 2024-08-11 at 12 59 40 PM](https://github.com/user-attachments/assets/8603f14c-2eab-4afb-86fc-29f2d05e8c3a)
![Screenshot 2024-08-11 at 12 59 47 PM](https://github.com/user-attachments/assets/ddb9b122-14f2-4f37-9e44-ae55e9b1ef6f)
![Screenshot 2024-08-11 at 12 59 54 PM](https://github.com/user-attachments/assets/e05624bc-03d2-48de-9ecf-1a70f45a20bb)
![Screenshot 2024-08-11 at 1 00 03 PM](https://github.com/user-attachments/assets/83814681-3fb7-4805-a209-fde7fc54f1e1)

**Comment by RitvikSardana** [comment]
Looking into it @dineshpanchal93

**Comment by dineshpanchal93** [comment]
https://github.com/user-attachments/assets/640b81ec-c6a7-4c90-ae8a-f9487473c0ab
