### ISSUE TITLE
Failed Installation

### ISSUE THREAD

**Issue by thegegi** [frappe/helpdesk#2070]
Installing frappe
$ /home/thegegi/Thegegi/env/bin/python -m pip install --quiet --upgrade -e /home/thegegi/Thegegi/apps/frappe
$ yarn install --check-files
Usage: yarn [options]

yarn: error: no such option: --check-files
subprocess.CalledProcessError: Command 'yarn install --check-files' returned non-zero exit status 2.
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/bench/commands/make.py", line 75, in init
    init(
  File "/usr/local/lib/python3.12/dist-packages/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/bench/utils/system.py", line 87, in init
    get_app(
  File "/usr/local/lib/python3.12/dist-packages/bench/app.py", line 778, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.12/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/bench/app.py", line 253, in install
    install_app(
  File "/usr/local/lib/python3.12/dist-packages/bench/app.py", line 923, in install_app
    bench.run(yarn_install, cwd=app_path)
  File "/usr/local/lib/python3.12/dist-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/bench/utils/__init__.py", line 181, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: yarn install --check-files

ERROR: There was a problem while creating Thegegi

**Comment by RitvikSardana** [comment]
Does not seem like a Helpdesk issue, please open it in Frappe Framework repo
https://github.com/frappe/frappe/issues/new
